#!/bin/bash
# ============================================================================
#  run_test.sh -- headless test harness for ~/drill/nvimrc.lua
#
#  Drives the real config in headless nvim, feeds a key sequence written in
#  nvim <> notation, and asserts the resulting buffer contents (and optionally
#  register contents).
#
#  USAGE
#    ./run_test.sh --name NAME --keys 'KEYS' \
#                  (--content 'TEXT' | --content-file PATH) \
#                  (--expect  'TEXT' | --expect-file  PATH) \
#                  [--ext py] [--cursor L:C] [--start insert|normal|append] \
#                  [--expect-reg 'NAME=VALUE']... [--verbose]
#
#    --content / --expect interpret backslash escapes: use \n for newlines.
#    --keys is taken RAW (no escape expansion); write keys in nvim notation,
#           e.g. '<S-Down><S-Down><C-_>' or '<C-a>X' or '<Esc>ggVG'.
#
#  EXIT CODES   0 = PASS   1 = FAIL (assertion)   2 = harness/nvim error
#
#  See NOTES.md in this directory for why the key feeding is shaped the way
#  it is (feedkeys mode 'xt', the leading 'i', the deferred startinsert).
# ============================================================================
set -uo pipefail

HARNESS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$HARNESS_DIR/.." && pwd)"
CONFIG="${DRILL_CONFIG:-$REPO_DIR/nvimrc.lua}"
NVIM="${NVIM_BIN:-nvim}"
PATH="$HARNESS_DIR/bin:$PATH"          # provides the `timeout` shim on macOS
export PATH

NAME=""; KEYS=""; CONTENT=""; CONTENT_FILE=""; EXPECT=""; EXPECT_FILE=""
EXT="txt"; CURSOR=""; START="insert"; VERBOSE=0
HAVE_CONTENT=0; HAVE_EXPECT=0
declare -a EXPECT_REGS=()

die() { printf 'run_test.sh: %s\n' "$*" >&2; exit 2; }

while [ $# -gt 0 ]; do
  case "$1" in
    --name)         NAME="$2"; shift 2 ;;
    --keys)         KEYS="$2"; shift 2 ;;
    --content)      CONTENT="$2"; HAVE_CONTENT=1; shift 2 ;;
    --content-file) CONTENT_FILE="$2"; HAVE_CONTENT=1; shift 2 ;;
    --expect)       EXPECT="$2"; HAVE_EXPECT=1; shift 2 ;;
    --expect-file)  EXPECT_FILE="$2"; HAVE_EXPECT=1; shift 2 ;;
    --expect-reg)   EXPECT_REGS+=("$2"); shift 2 ;;
    --ext)          EXT="$2"; shift 2 ;;
    --cursor)       CURSOR="$2"; shift 2 ;;
    --start)        START="$2"; shift 2 ;;
    --verbose|-v)   VERBOSE=1; shift ;;
    -h|--help)      sed -n '2,25p' "$0"; exit 0 ;;
    *)              die "unknown argument: $1" ;;
  esac
done

[ -n "$NAME" ]     || die "--name is required"
[ -n "$KEYS" ]     || die "--keys is required"
[ "$HAVE_CONTENT" = 1 ] || die "--content or --content-file is required"
[ "$HAVE_EXPECT"  = 1 ] || die "--expect or --expect-file is required"
[ -r "$CONFIG" ]   || die "config not readable: $CONFIG"
case "$NAME" in *[!A-Za-z0-9._-]*) die "--name must match [A-Za-z0-9._-]+" ;; esac

case "$START" in
  insert) PREFIX='i' ;;   # reproduces the config's :startinsert (== `i`)
  append) PREFIX='A' ;;   # insert at end of line (== :startinsert!)
  normal) PREFIX=''  ;;   # normal mode (deferred startinsert is disarmed first)
  *) die "--start must be insert|normal|append" ;;
esac

WORK="$HARNESS_DIR/work/$NAME.$$"
rm -rf "$WORK"; mkdir -p "$WORK" || die "cannot create $WORK"

FIXTURE="$WORK/fixture.$EXT"
OUT="$WORK/out.actual"
WANT="$WORK/out.expected"
KEYFILE="$WORK/keys.txt"
DRIVER="$WORK/driver.lua"
REPORT="$WORK/report.json"
STDERR="$WORK/nvim.stderr"

# ---- fixture -------------------------------------------------------------
if [ -n "$CONTENT_FILE" ]; then
  cp "$CONTENT_FILE" "$FIXTURE" || die "cannot read --content-file $CONTENT_FILE"
else
  printf '%b' "$CONTENT" > "$FIXTURE"
fi
# guarantee exactly one trailing newline (nvim writes one back)
python3 - "$FIXTURE" <<'PY'
import sys
p = sys.argv[1]
d = open(p, 'rb').read()
open(p, 'wb').write(d.rstrip(b'\n') + b'\n' if d else b'\n')
PY

# ---- expectation ---------------------------------------------------------
if [ -n "$EXPECT_FILE" ]; then
  cp "$EXPECT_FILE" "$WANT" || die "cannot read --expect-file $EXPECT_FILE"
else
  printf '%b' "$EXPECT" > "$WANT"
fi
python3 - "$WANT" <<'PY'
import sys
p = sys.argv[1]
d = open(p, 'rb').read()
open(p, 'wb').write(d.rstrip(b'\n') + b'\n' if d else b'\n')
PY

# ---- keys (raw, no escape expansion) -------------------------------------
printf '%s' "$PREFIX$KEYS" > "$KEYFILE"

# ---- driver --------------------------------------------------------------
CURSOR_LUA=""
if [ -n "$CURSOR" ]; then
  CL="${CURSOR%%:*}"; CC="${CURSOR##*:}"
  CURSOR_LUA="vim.fn.cursor($CL, $CC)"
fi

cat > "$DRIVER" <<LUA
-- generated by run_test.sh -- do not edit
local WORK   = '$WORK'
local report = { }

-- 1. Let the config's BufEnter -> vim.schedule(startinsert) callback run.
--    (It is queued during startup; vim.wait() pumps the event loop so it
--     fires deterministically before we touch anything.)
vim.wait(60)

-- 2. Disarm any pending :startinsert. Inside a -c command mode() still
--    reports "n" while restart_edit is armed; the first fed key would then
--    be SWALLOWED by the transition into Insert. stopinsert clears it, so
--    the run is deterministic regardless of scheduling.
pcall(vim.cmd, 'stopinsert')

$CURSOR_LUA

-- The config sets clipboard=unnamedplus, so '+' really is the macOS
-- pasteboard and would otherwise leak between runs. Start every test clean.
pcall(vim.fn.setreg, '+', '')
pcall(vim.fn.setreg, '"', '')

report.mode_before = vim.fn.mode(1)
report.buf_before  = vim.api.nvim_buf_get_name(0)

-- 3. Read the key sequence raw from disk -- keeps every backslash, quote and
--    angle bracket intact, no shell/lua quoting hazards.
local fh = assert(io.open(WORK .. '/keys.txt', 'rb'))
local KEYS = fh:read('*a'); fh:close()
KEYS = KEYS:gsub('\n\$', '')

-- 4. THE RECIPE. One single call, mode 'xt':
--      x = execute the typeahead now, in this call
--      t = handle the keys "as if typed"  <-- REQUIRED, see NOTES.md:
--          without it 'keymodel=startsel'+'selectmode=key' produce VISUAL
--          mode instead of SELECT mode and the whole config misbehaves.
--    Never add '!' -- 'xt!' does not end Insert mode and headless nvim hangs.
local ok, err = pcall(vim.api.nvim_feedkeys,
  vim.api.nvim_replace_termcodes(KEYS, true, false, true), 'xt', false)
report.feedkeys_ok  = ok
report.feedkeys_err = ok and vim.NIL or tostring(err)

-- 5. Let any <Cmd>/vim.schedule work triggered by the mapping settle.
vim.wait(60)

report.mode_after = vim.fn.mode(1)
report.line       = vim.fn.line('.')
report.col        = vim.fn.col('.')
report.buf_after  = vim.api.nvim_buf_get_name(0)
report.wins       = #vim.api.nvim_list_wins()
report.reg_plus   = vim.fn.getreg('+')
report.reg_unnamed= vim.fn.getreg('"')
report.reg_star   = vim.fn.getreg('*')
report.mark_lt    = vim.fn.getpos("'<")[2]
report.mark_gt    = vim.fn.getpos("'>")[2]

vim.fn.writefile({ vim.json.encode(report) }, WORK .. '/report.json')
LUA

# ---- run -----------------------------------------------------------------
# Subshell + redirect keeps bash from printing "Alarm clock: 14" when the
# 20s guard fires; the rc still reaches us.
( timeout 20 "$NVIM" --headless -u "$CONFIG" "$FIXTURE" \
    -c "lua dofile('$DRIVER')" \
    -c "w! $OUT" \
    -c 'qa!' >"$STDERR" 2>&1 ) 2>/dev/null
RC=$?

STATUS="PASS"; REASON=""

if [ "$RC" -ne 0 ]; then
  STATUS="ERROR"
  if [ "$RC" -ge 124 ]; then REASON="nvim timed out or was killed (rc=$RC) -- the key sequence probably left nvim waiting for input"
  else REASON="nvim exited rc=$RC"; fi
elif [ ! -f "$OUT" ]; then
  STATUS="ERROR"; REASON="nvim never wrote the output buffer"
fi

# ---- assertions ----------------------------------------------------------
DIFF=""
if [ "$STATUS" = "PASS" ]; then
  DIFF="$(diff -u --label expected "$WANT" --label actual "$OUT" 2>&1)"
  if [ -n "$DIFF" ]; then STATUS="FAIL"; REASON="buffer contents differ"; fi
fi

if [ "$STATUS" = "PASS" ] && [ "${#EXPECT_REGS[@]}" -gt 0 ] && [ -f "$REPORT" ]; then
  for spec in "${EXPECT_REGS[@]}"; do
    rname="${spec%%=*}"; rwant="${spec#*=}"
    rgot="$(python3 - "$REPORT" "$rname" <<'PY'
import json, sys
r = json.load(open(sys.argv[1]))
key = {'+':'reg_plus', '*':'reg_star', '"':'reg_unnamed'}.get(sys.argv[2])
sys.stdout.write('' if key is None else str(r.get(key, '')))
PY
)"
    rwant_x="$(printf '%b' "$rwant")"
    if [ "$rgot" != "$rwant_x" ]; then
      STATUS="FAIL"; REASON="register '$rname' = [$rgot], expected [$rwant_x]"; break
    fi
  done
fi

# ---- report --------------------------------------------------------------
case "$STATUS" in
  PASS)  printf '\033[32mPASS\033[0m  %s\n' "$NAME" ;;
  FAIL)  printf '\033[31mFAIL\033[0m  %s  -- %s\n' "$NAME" "$REASON" ;;
  ERROR) printf '\033[33mERROR\033[0m %s  -- %s\n' "$NAME" "$REASON" ;;
esac

if [ "$STATUS" != "PASS" ] || [ "$VERBOSE" = 1 ]; then
  printf '      keys   : %s\n' "$PREFIX$KEYS"
  printf '      fixture: %s\n' "$FIXTURE"
  if [ -n "$DIFF" ]; then
    printf '      ---- diff (expected vs actual) ----\n'; printf '%s\n' "$DIFF" | sed 's/^/      /'
  elif [ -f "$OUT" ]; then
    printf '      ---- actual buffer ----\n'; sed 's/^/      /' "$OUT"
  fi
  if [ -f "$REPORT" ]; then
    printf '      ---- state ----\n'
    python3 - "$REPORT" <<'PY' | sed 's/^/      /'
import json, sys
r = json.load(open(sys.argv[1]))
for k in ('mode_before','mode_after','line','col','wins','feedkeys_ok','feedkeys_err',
          'reg_plus','reg_unnamed','mark_lt','mark_gt'):
    if k in r: print(f'{k:13}= {r[k]!r}')
PY
  fi
  # nvim always echoes the ":w!" message; only surface real E-errors here.
  if grep -qE 'E[0-9]{2,4}:|Error' "$STDERR" 2>/dev/null; then
    printf '      ---- nvim errors (full log: %s) ----\n' "$STDERR"
    grep -oE 'E[0-9]{2,4}:[^"]*' "$STDERR" | sed 's/^/      /'
  fi
fi

case "$STATUS" in PASS) exit 0 ;; FAIL) exit 1 ;; *) exit 2 ;; esac
